configurations/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/', include('stockManager.urls')),
    path('home/', include('home.urls')),
    path('', include('stockManager.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
path('dashboard/', views.index,name='index'),
path('about/', views.aboutPage,name='about'),

]

stockManager/urls.py
from django.urls import path
from . import views

app_name = 'stockManager'

urlpatterns = [
    #Authentication patterns
path('',views.loginPage,name='login'),
path('logout',views.logoutUser,name='logout'),
path('register/',views.register,name='register'),
    #Product patterns
path('addProduct/',views.addProductForm,name='addProduct'),
path('allProducts/',views.allProducts,name='allProducts'),
path('updateProduct/<int:productId>',views.updateProducts,name='updateProduct'),
path('deleteProduct/<int:productId>',views.deleteProduct,name='deleteProduct'),
    #Customer Patters 
path('addCustomer/',views.addCustomerForm,name='addCustomer'),
path('allCustomers/',views.allCustomers,name='allCustomers'),
path('updateCustomer/<int:customerId>',views.updateCustomer,name='updateCustomer'),
path('deleteCustomer/<int:customerId>',views.deleteCustomer,name='deleteCustomer'),

path('addExpense/',views.expenseAddForm,name='addExpense'),
path('allExpenses/',views.allExpenses,name='allExpenses'),
path('updateExpense/<int:expenseId>',views.updateExpense,name='updateExpense'),
path('deleteExpense/<int:expenseId>',views.deleteExpense,name='deleteExpense'),

    #Order patterns 
path('addOrder/',views.addOrdersForm,name='addOrder'),
path('allOrders/',views.allOrders,name='allOrders'),
path('updateOrder/<int:orderId>',views.updateOrders,name='updateOrder'),
path('deleteOrder/<int:orderId>',views.deleteOrder,name='deleteOrder'),
path('pendingOrders/',views.pendingOrders,name='pendingOrders'),
path('fulfilledOrders/',views.fulfilledOrders,name='fulfilledOrders'),


    #sale patterrns
path('addSale/',views.addSalesForm,name='addSale'),
path('allSales/',views.allSales,name='allSales'),
path('outstandingInvoices/',views.outstandingInvoices,name='outstandingInvoices'),
# path('updateOrder/<int:orderId>',views.updateOrders,name='updateOrder'),
# path('deleteOrder/<int:orderId>',views.deleteOrder,name='deleteOrder'),





]

stockManager/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product, Customer,Order,Sale,Expense
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm









class ProductAddForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'quantityProduced', 'quantityPacked', 'pricePerLitre', 'pricePerHalfLitre','description',]

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'quantityProduced':forms.NumberInput(attrs={'class':'form-control'}),
            'quantityPacked':forms.NumberInput(attrs={'class':'form-control'}),
            'pricePerLitre':forms.TextInput(attrs={'class':'form-control'}),
            'pricePerHalfLitre':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
        }

class CustomerAddForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'phone','location',]

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'phone':forms.TextInput(attrs={'class':'form-control'}),
            'location':forms.TextInput(attrs={'class':'form-control'}),
        }
        
class OrderAddForm(ModelForm):
    class Meta:
        model = Order
        fields =['customer','product','quantity_in_litres','selling_price','sold_at','amount_paid','packaging','delivery','order_status',]


        widgets = {
            'customer':forms.Select(attrs={'class':'form-control'}),
            'product':forms.Select(attrs={'class':'form-control'}),
            'quantity_in_litres':forms.NumberInput(attrs={'class':'form-control'}),
            'selling_price':forms.NumberInput(attrs={'class':'form-control'}),
            'sold_at':forms.NumberInput(attrs={'class':'form-control'}),
            'amount_paid':forms.NumberInput(attrs={'class':'form-control'}),
            'packaging':forms.Select(attrs={'class':'form-control'}),
            'delivery':forms.Select(attrs={'class':'form-control'}),
            'order_status':forms.Select(attrs={'class':'form-control'}),
        }


class SaleAddForm(ModelForm):
      class Meta:
        model = Sale
        fields =['customer','product','pieces','selling_price','packaging',]



        widgets = {
            'customer':forms.Select(attrs={'class':'form-control'}),
            'product':forms.Select(attrs={'class':'form-control'}),
            'packaging':forms.Select(attrs={'class':'form-control'}),
            'pieces':forms.NumberInput(attrs={'class':'form-control'}),
            'selling_price':forms.TextInput(attrs={'class':'form-control'}),
        }

class userRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields =['email','username','password1','password2',]


        widgets = {
            'email':forms.Select(attrs={'class':'form-control'}),
            'username':forms.Select(attrs={'class':'form-control'}),
            'password1':forms.NumberInput(attrs={'class':'form-control'}),
            'password2':forms.Select(attrs={'class':'form-control'}),
        }


class ExpenseAddForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['expense_tittle','amount_spent',]

        widgets = {
            'expense_tittle':forms.TextInput(attrs={'class':'form-control'}),
            'amount_spent':forms.NumberInput(attrs={'class':'form-control'}),
        }

stockManager/views.py
from django.shortcuts import render,redirect
from .forms import ProductAddForm,CustomerAddForm,OrderAddForm,SaleAddForm,userRegisterForm,ExpenseAddForm
from django.http import HttpResponseRedirect
from .models import Product,Customer,Order,Expense
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.

# Controller logic for a product 
@login_required(login_url='/')
def addProductForm (request):
    if request.method == 'POST':
        submitted = False
        form =ProductAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Product Added Successfully')
            return HttpResponseRedirect('/stock/allProducts?submitted=True')
        else:
            messages.error(request,'Something went wrong , please try again later')

    else:
        form=ProductAddForm()
        submitted=False
        if 'submitted' in request.GET:
            submitted=True
    return render(request,'stockManager/addProduct.html',{'form':form,'submitted':submitted})
@login_required(login_url='/')
def allProducts(request):
    products = Product.objects.all()
    return render(request,'stockManager/allProducts.html',{'products':products})


@login_required(login_url='/')
def updateProducts(request,productId):
    product = Product.objects.get( pk=productId)
    form = ProductAddForm(request.POST or None,instance=product)
    if form.is_valid():
        form.save()
        messages.success(request,'Product Details Updated Successfully')
        return redirect('/stock/allProducts')

    return render(request , 'stockManager/productUpdate.html',{'product':product,'form':form})


@login_required(login_url='/')
def deleteProduct (request , productId):
    product = Product.objects.get(pk=productId)
    product.delete()
    return redirect ('/stock/allProducts')
    
# Controller logics for a customer 

@login_required(login_url='/')
def addCustomerForm (request):
    if request.method == 'POST':
        submitted = False
        form =CustomerAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Customer Added Successfully')
            return HttpResponseRedirect('/stock/allCustomers?submitted=True')
        
        

    else:
        form=CustomerAddForm()
        submitted=False
        if 'submitted' in request.GET:
            submitted=True
    return render(request,'stockManager/addCustomer.html',{'form':form,'submitted':submitted})



@login_required(login_url='/')
def allCustomers(request):
    customers = Customer.objects.all()
    return render(request,'stockManager/allCustomers.html',{'customers':customers})


@login_required(login_url='/')
def updateCustomer(request,customerId):
    customer = Customer.objects.get( pk=customerId)
    form = CustomerAddForm(request.POST or None,instance=customer)
    if form.is_valid():
        form.save()
        messages.success(request,'Customer Details  Updated Successfully')
        return redirect('/stock/allCustomers')

    return render(request , 'stockManager/customerUpdate.html',{'customer':customer,'form':form})

def deleteCustomer (request , customerId):
    customer = Customer.objects.get(pk=customerId)
    customer.delete()
    return redirect ('/stock/allCustomers')
    



# Controller logics for expenses 

@login_required(login_url='/')
def expenseAddForm (request):
    if request.method == 'POST':
        submitted = False
        form =ExpenseAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Expense Recorded Successfully')
            return HttpResponseRedirect('/stock/allExpenses?submitted=True')
        
        

    else:
        form=ExpenseAddForm()
        submitted=False
        if 'submitted' in request.GET:
            submitted=True
    return render(request,'stockManager/addExpense.html',{'form':form,'submitted':submitted})



@login_required(login_url='/')
def allExpenses(request):
    expenses = Expense.objects.all()
    return render(request,'stockManager/allExpenses.html',{'expenses':expenses})




@login_required(login_url='/')
def updateExpense(request,expenseId):
    expense = Expense.objects.get( pk=expenseId)
    form = ExpenseAddForm(request.POST or None,instance=expense)
    if form.is_valid():
        form.save()
        messages.success(request,'Expenses Updated Successfully')
        return redirect('/stock/allExpenses')

    return render(request , 'stockManager/expenseUpdate.html',{'expense':expense,'form':form})

def deleteExpense (request , expenseId):
    expense = Expense.objects.get(pk=expenseId)
    expense.delete()
    return redirect ('/stock/allExpenses')
    


# controller logics for the order model
@login_required(login_url='/')
def addOrdersForm (request):
    if request.method == 'POST':
        submitted = False
        form =OrderAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Order Placed Successfully')
            return HttpResponseRedirect('/stock/allOrders?submitted=True')
        
        

    else:
        form=OrderAddForm()
        submitted=False
        if 'submitted' in request.GET:
            submitted=True
    return render(request,'stockManager/addOrders.html',{'form':form,'submitted':submitted})


@login_required(login_url='/')
def allOrders(request):
    orders = Order.objects.all()
    return render(request,'stockManager/allOrders.html',{ 'orders':orders })


@login_required(login_url='/')
def pendingOrders(request):
    orders = Order.objects.filter(order_status='pending')
    return render(request,'stockManager/allOrders.html',{'orders':orders})


@login_required(login_url='/')
def fulfilledOrders(request):
    orders = Order.objects.filter(order_status='fulfilled')
    return render(request,'stockManager/allOrders.html',{'orders':orders})


@login_required(login_url='/')
def updateOrders(request,orderId):
    order = Order.objects.get( pk=orderId)
    form = OrderAddForm(request.POST or None,instance=order)
    if form.is_valid():
        form.save()
        messages.success(request,'Order Information Updated Successfully')
        return redirect('/stock/allOrders')

    return render(request , 'stockManager/orderUpdate.html',{'order':order,'form':form})


@login_required(login_url='/')
def deleteOrder (request , orderId):
    order = Order.objects.get(pk=orderId)
    order.delete()
    return redirect ('/stock/allOrders')


@login_required(login_url='/')
# controller logic for the sales controller
def addSalesForm (request):
    if request.method == 'POST':
        submitted = False
        form =SaleAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Sales  Recorded Successfully')
            return HttpResponseRedirect('/stock/allSales?submitted=True')
        
        

    else:
        form=SaleAddForm()
        submitted=False
        if 'submitted' in request.GET:
            submitted=True
    return render(request,'stockManager/addSale.html',{'form':form,'submitted':submitted})



@login_required(login_url='/')
def allSales(request):
    sales = Order.objects.filter (sold_at__gt=0 )
    
    return render(request,'stockManager/allSales.html',{'sales':sales})



@login_required(login_url='/')
def outstandingInvoices(request):
    #getting the list of sales where customers still have a balance due.
    sales = Order.objects.filter (balance__gt=0 )
    
    return render(request,'stockManager/allSales.html',{'sales':sales})




#contains logic for authentication
def loginPage (request):
    if request.user.is_authenticated:
       return redirect('home/dashboard')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                messages.success(request,'Log-In Successful')
                return redirect('/home/dashboard')
            else:
                messages.info(request,'Username or Password is incorrect')
            
        context = {}    
        return render(request,'stockManager/login.html' , context)


#logout logic
def logoutUser (request):
    logout(request)
    messages.success(request,'Log-Out Successful')
    return redirect('/')

@login_required(login_url='/')
def register (request):
    if request.user.is_authenticated:
       return redirect('home/dashboard')
    else:
        form = userRegisterForm()
        if request.method == 'POST':
            form = userRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request,'Account Created Successfully For ' + user )
                return redirect('/')
            else:
                print(form.errors)
        return render(request,'stockManager/register.html' , {'form':form})

templates/stockManager/addCustomer.html
{% extends 'base.html' %} 
{% block content %}
<form class="mt-5" action="" method="POST">
  <h5 class="form-header text-decoration-underline  w-bold text-start">ADD CUSTOMER</h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:allCustomers'%}" class="text-secondary text-decoration-none" >Customers</a></li>
    </ol>
  </nav>
  <hr>
  {% csrf_token %}
  <div class="form-group">
   {{form}}
  <button type="submit" class="btn btn-primary mt-3">Add Customer</button>
</form>
{% endblock %}

templates/stockManager/addExpense.html
{% extends 'base.html' %} 
{% block content %}
<form class="mt-5" action="" method="POST">
  <h5 class="form-header text-decoration-underline  w-bold text-start">RECORD EXPENSE</h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:allExpenses'%}" class="text-secondary text-decoration-none" >Expenses</a></li>
    </ol>
  </nav>
  <hr>
  {% csrf_token %}
  <div class="form-group">
   {{form}}
  <button type="submit" class="btn btn-primary mt-3">Add Expense</button>
</form>
{% endblock %}

templates/stockManager/addOrders.html
{% extends 'base.html' %} 
{% block content %}
<div>
  <form class="mt-5" action="" method="POST">
    <h5 class="text-decoration-underline form-header w-bold text-start mt-2"> ORDER REGISTRATION </h5>
    <nav aria-label="breadcrumb ">
      <ol class="breadcrumb mt-0 mb-5">
        <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:allOrders'%}" class="text-secondary text-decoration-none" >Orders</a></li>
      </ol>
    </nav>
  <hr>
  {% csrf_token %}
  <div class="form-group">
   {{form}}
  <button type="submit" class="btn btn-primary mt-3">Save Order</button>
</form>
{% endblock %}

templates/stockManager/addSale.html
{% extends 'base.html' %} 
{% block content %}

<form class="mt-5" action="" method="POST">
  <h5 class="text-decoration-underline form-header  w-bold text-start"> Sales Record </h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:allSales'%}" class="text-secondary text-decoration-none" >Sales</a></li>
    </ol>
  </nav>
  <hr>
  {% csrf_token %}
  <div class="form-group">
   {{form}}
  <button type="submit" class="btn btn-primary ">Add Sale</button>
</form>
{% endblock %}

templates/stockManager/allCustomers.html
{% extends 'base.html'%} {% block content%}

{%if messages %} 
{%for message in messages %}
<div class="mt-5 alert alert-success alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="close">
    x
  </button>
</div>

{% endfor %} 
{%endif%}
<br />
<table class="table table-striped table-bordered">
  <h5 class="form-header  w-100 text-start text-decoration-underline mt-2">
       CUSTOMER RECORDS
  </h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:addCustomer'%}" class="text-secondary text-decoration-none" >Add Customer</a></li>
    </ol>
  </nav>
  <hr>
  <thead class="thead-dark" >
    <th scope="col"></th>
    <th scope="col">Customer Name</th>
    <th scope="col">Phone Number</th>
    <th scope="col">Location</th>
    <th scope="col">Action</th>
  </thead>
  <tbody>
    {% for customer in customers %}
    <tr>
      <th scope="row">{{customer.id}}</th>
      <td>{{customer.name}}</td>
      <td>{{customer.phone}}</td>
      <td>{{customer.location}}</td>
      <td>
        <div class="d-flex justify-content-between">
          <a
            href="{% url 'stockManager:updateCustomer' customer.id %}"
            type="button"
            class="btn btn-outline-secondary "
            >Update
          </a>
          <a
            href="{% url 'stockManager:deleteCustomer' customer.id %}"
            type="button"
            class="btn btn-outline-danger "
            >Delete</a
          >
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/stockManager/allExpenses.html
{% extends 'base.html'%} {% block content%}

{%if messages %} 
{%for message in messages %}
<div class="mt-5 alert alert-success alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="close">
    x
  </button>
</div>

{% endfor %} 
{%endif%}
<br />
<table class="table table-striped table-bordered">
  <h5 class="form-header  w-100 text-start text-decoration-underline mt-2">
       EXPENSE LIST
  </h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:addCustomer'%}" class="text-secondary text-decoration-none" >Add Customer</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:addExpense'%}" class="text-secondary text-decoration-none" > Record Expense </a></li>
    </ol>
  </nav>
  <hr>
  <thead class="thead-dark" >
    <th scope="col"></th>
    <th scope="col">Date Spent</th>
    <th scope="col">Expense  Tittle</th>
    <th scope="col">Amount</th>
  </thead>
  <tbody>
    {% for expense in expenses %}
    <tr>
      <th scope="row">{{customer.id}}</th>
      <td>{{expense.date}}</td>
      <td>{{expense.expense_tittle}}</td>
      <td>{{expense.amount_spent}}</td>
      <td>
        <div class="d-flex justify-content-between">
          {% comment %} <a
            href="{% url 'stockManager:updateExpense' expense.Id %}"
            type="button"
            class="btn btn-outline-secondary "
            >Update
          </a> {% endcomment %}
          {% comment %} <a
            href="{% url 'stockManager:deleteExpense' expense.Id %}"
            type="button"
            class="btn btn-outline-danger "
            >Delete</a
          >
        </div> {% endcomment %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/stockManager/allOrders.html
{% extends 'base.html'%} {% block content%}

{%if messages %} 
{%for message in messages %}
<div class="mt-5 alert alert-success alert-dismissible fw-bold text-center fade show" role="alert">
  {{message}}
</div>

{% endfor %} 
{%endif%}
<br />
<table class="table table-striped table-bordered">
  <h5 class="form-header w-100 text-start text-decoration-underline mt-2">
       ORDER RECORDS
  </h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:addOrder'%}" class="text-secondary text-decoration-none" >Add Order</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:allSales'%}" class="text-secondary text-decoration-none" >View Sales</a></li>
    </ol>
  </nav>
  <hr>

  <thead class="thead-dark" >
    <th scope="col"></th>
    <th scope="col">Date Ordered</th>
    <th scope="col">Customer Name</th>
    <th scope="col">Product Name</th>
    <th scope="col">Quantity(L)</th>
    <th scope="col">Selling Price</th>
    <th scope="col">Sold At</th>
    <th scope="col">Amount Paid</th>
    <th scope="col">Packaging</th>
    <th scope="col">Delivery Status</th>
    <th scope="co1 ">Order Status</th>
    <th scope="co1 ">Action</th>
  </thead>
  <tbody>
    {% if orders%}
    {% for order in orders %}
    <tr>
      <th scope="row">{{order.id}}</th>
      <td>{{order.date_created}}</td>
      <td>{{order.customer}}</td>
      <td>{{order.product}}</td>
      <td>{{order.quantity_in_litres}}</td>
      <td>{{order.selling_price}}</td>
      <td>{{order.sold_at}}</td>
      <td>{{order.amount_paid}}</td>
      <td>{{order.packaging}}</td>
      <td>{{order.delivery}}</td>
      <td>{{order.order_status}}</td>
      <td>
        <div class="d-flex justify-content-end ">
          <a
            href="{% url 'stockManager:updateOrder' order.id %}"
            type="button"
            class="btn btn-outline-secondary ms-2 "
            >Update
          </a>
          <a
            href="{% url 'stockManager:deleteOrder' order.id %}"
            type="button"
            class="btn btn-outline-danger ms-2 "
            >Delete</a
          >
        </div>
      </td>
    </tr>
    {% endfor %}
    {% else %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      Currently there are no pending orders in the database.
      <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {%endif%}
  </tbody>
</table>
{% endblock %}

templates/stockManager/allSales.html
{% extends 'base.html'%} {% block content%}

{%if messages %} 
{%for message in messages %}
<div class="mt-5 alert alert-success alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="close">
    x
  </button>
</div>

{% endfor %} 
{%endif%}
<br />
<table class="table table-striped table-bordered">
  <h5 class="form-header w-100 text-start text-decoration-underline mt-2">
       SALES DATA
  </h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:addSale'%}" class="text-secondary text-decoration-none" >Add Sale</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:fulfilledOrders' %}" class="text-secondary text-decoration-none" >Fullfilled Orders </a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:pendingOrders' %}" class="text-secondary text-decoration-none" >Pending Orders</a></li>
    </ol>
  </nav>
  <hr>

  <thead class="thead-dark" >
    <th scope="col"></th>
    <th scope="col">Date Sold</th>
    <th scope="col">Customer Name</th>
    <th scope="col">Product Name</th>
    <th scope="col">Quantity(L)</th>
    <th scope="col">Sold At</th>
    <th scope="col">Amount Paid</th>
    <th scope="col">Balance Due</th>

 
  </thead>
  <tbody>
    {% if sales%}
    {% for sale in sales %}
    <tr>
      <th scope="row">{{sale.id}}</th>
      <td>{{sale.date_created}}</td>
      <td>{{sale.customer}}</td>
      <td>{{sale.product}}</td>
      <td>{{sale.quantity_in_litres}}</td>
      <td>{{sale.sold_at}}</td>
      <td>{{sale.amount_paid}}</td>
      <td>{{sale.balance}}</td>
     
    </tr>
    {% endfor %}
    {% else %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      Currently there are no sales recorded in the database.
      <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {%endif%}
  </tbody>
</table>
{% endblock %}

templates/stockManager/customerUpdate.html
{% extends 'base.html' %} 
{% block content %}

{%if submitted%}
{%else%}
<form class="mt-5" action="" method="POST">
  <h5 class="form-header  w-bold text-center">CUSTOMER INFORMATION UPDATE</h5>
  <nav aria-label="breadcrumb ">
    <ol class="breadcrumb mt-0 mb-5">
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'home:index'%}" class="text-secondary text-decoration-none" >Home</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a href="{% url 'stockManager:allCustomers'%}" class="text-secondary text-decoration-none" >Our Customers</a></li>
    </ol>
  </nav>
  <hr>
  {% csrf_token %}
  <div class="form-group">
   {{form}}
  <button type="submit" class="btn btn-primary mt-3 ">Update</button>
</form>
{%endif%}
{% endblock %}